import {
  FOAL_MILESTONE_KEYS as SHARED_FOAL_MILESTONE_KEYS,
  FOAL_MILESTONE_LABELS as SHARED_FOAL_MILESTONE_LABELS,
} from '@/models/enums';

export const FOAL_MILESTONE_KEYS = SHARED_FOAL_MILESTONE_KEYS;
export const FOAL_MILESTONE_LABELS = SHARED_FOAL_MILESTONE_LABELS;
